### ISSUE TITLE
Files required for part 1

### ISSUE THREAD

**Issue by fredjaya** [Sydney-Informatics-Hub/hello-nextflow#12]
Hey @christopher-hakkaart, I'm configuring the directory structure and files for the VMs - will part 1 require any files available from the get-go? i.e. the [hello-world.nf section](https://github.com/Sydney-Informatics-Hub/hello-nextflow/blob/main/docs/part1/03_hellonf.md#hello-worldnf)?

Aiming to have the directory structure on the VM  with a `~/part1/` and `~/part2/` dirs and only the relevant files in the respective dirs (i.e. not cloning the whole git repo, no docs)

**Comment by christopher-hakkaart** [comment]
Hey @fredjaya - no files are required for part 1.

**Comment by fredjaya** [comment]
Thanks!
