### ISSUE TITLE
Comments for day 2

### ISSUE THREAD

**Issue by christopher-hakkaart** [Sydney-Informatics-Hub/hello-nextflow#2]
Hey! Things are shaping up nicely!

I've skimmed the material and have a few minor comments you might consider:

1. Is the `log.info` needed? The main point of this section is to show that you can change parameters and they log changes (a very visible way to view parameter changes). Otherwise it is a little redundant for a "new" Nextflow user who will be primarily fouced on building a pipeline rather than showing logs.
2. I would recommend adding a container for each process, and that this should be introduced early. The way you have included is a hangover from DSL1 where it would be one big container for a whole pipeline. It's now recommended to have a single container for a single process to ease of development and configuration.
3. While the concepts of operators and channel factories will be introduced in session 1, they are difficult concepts to grasp for new users, so don't be afraid to slow this part down and link out to the docs to show the full range. I would expand the MULTIQC section to explain this further.
4. You could consider adding a simple samplesheet (see the nf-core configure workshop for an example; data could be stored in the repo and pulled for this workshop to keep it neat)
5. A visible params example would be a good addition (either using the log as described above or a skip step; see the nf-core developer workshop for an example)

Otherwise looking great!

**Comment by fredjaya** [comment]
Awesome, thanks for the comments! 

I'll look at incorporating these and ping you once it's ready for another look over.
